version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./sql:/var/www/html/sql

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sample
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    ports:
      - "3306:3306"
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
